# Setup maven
---

- name: Download Maven redistribution package
  get_url:
    url: "{{ maven_mirror_url_binaries }}/{{ maven_package_filename }}"
    dest: "{{ remote_ansible_data_path }}/{{ maven_package_filename }}"
    timeout: 30

- name: Install Maven
  unarchive:
    src: "{{ remote_ansible_data_path }}/{{ maven_package_filename }}"
    dest: "{{ maven_install_dir }}"
    copy: false
    creates: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}"

- name: Symlink installed Maven version to make it available to the system
  file:
    state: link
    force: true
    src: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
    dest: "{{ maven_bin_path }}/mvn"
